### PR TITLE
Add ability to setup repo with env

### PR DESCRIPTION
**Pull request by marocchino**
I should use github_token since I can not use ssh key in my deployment env.
Also, I can not write in `_config.yml` because it is public repo.

So, I make this PR. :3

### CODE REVIEW

**Comment by Xuanwo** [comment]
Please let jscs happly,  https://travis-ci.org/hexojs/hexo-deployer-git/jobs/158928547#L506-L523

**Comment by marocchino** [comment]
Oops. @Xuanwo fix it. :bowtie:

**Comment by Xuanwo** [comment]
LGTM

**Comment by JackuB** [comment]
Is this feature released on npm? Tried to use it today, but had no luck. It was merged after current 0.2.0 that's on npm.

**Comment by NoahDragon** [comment]
@JackuB You could modify the package.json to set:
```
"hexo-deployer-git": "hexojs/hexo-deployer-git"
```

Then run `npm install`, it will get the latest development version.

**Comment by JackuB** [comment]
@NoahDragon yeah, but that kind of misses the point of versioning/package system. Switching to something like https://github.com/semantic-release/semantic-release can automate release process - I can prepare a PR with semrel if maintainer is interested.

**Pull request merged**
