### PR TITLE
Add initial support to config user.name & user.email

### PR DESCRIPTION
**Pull request by iamcco**

### CODE REVIEW

**Comment by Xuanwo** [comment]
Can I have a demo ?

**Comment by iamcco** [comment]
@Xuanwo 
_config.yml
``` 
deploy:
  type: git
  repo: xxx
  branch: xxx
  name: iamcco
  email: ooiss@qq.com
```
using particular github config different from my global config witch just for work

**Comment by Xuanwo** [comment]
OK, I got it, thank you for your work.
And can you update the test at the same time?

**Comment by leesei** [comment]
+1

Can you also update the README?

**Comment by leesei** [comment]
Merged.

**Pull request closed without merging**
